---
title: MH Resources
timezone: GMT
collections:
  people:
    title: People
    output: true
    permalink: "/about/:path/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
url: http://mhresources.tk
logo: "/img/logo-retina.png"
google_site_verification: 
lang: pt_PT
sitemap:
  priority_name: priority
short_title: MH Resources
description: Consultoria em Saúde Mental
baseurl: "/mhresources.tk"
permalink: "/:path/"
jekyll-archives:
  enabled: all
  layout: archive
plugins:
- jekyll-seo-tag
- jekyll-menus
- jekyll-feed
- jekyll-archives
