---
title: MH Resources - Saúde Mental
timezone: GMT
params:
  description: Consultoria em Saúde Mental e referenciação de serviços de internamento psiquiátrico em Aveiro, Coimbra e Lisboa.
  images:
  - /img/logo-retina.png
  title: MH Resources - Saúde Mental
taxonomies:
  series: series
collections:
  people:
    title: People
    output: true
    permalink: "/about/:path/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
url: https://mhresources.pt
logo: "/img/logo-retina.png"
google_site_verification:
lang: pt_PT
sitemap:
  priority_name: priority
short_title: MH Resources
description: Consultoria em Saúde Mental e referenciação de serviços de internamento psiquiátrico em Aveiro, Coimbra e Lisboa.
baseurl:
permalink: "/:path/"
jekyll-archives:
  enabled: all
  layout: archive
plugins:
- jekyll-seo-tag
- jekyll-menus
- jekyll-feed
- jekyll-archives
