---
title: MH Resources
timezone: GMT
url: http://mhresources.tk
logo: /img/logo-retina.png
google_site_verification:
lang: pt_PT
sitemap:
  exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "/about/index.html"
        - "/about/charlize-babatunde/index.html"
        - "/about/grady-nerio/index.html"
        - "/about/kellie-brewer/index.html"
        - "/about/martin-marino/index.html"
        - "/about/mary-ann-macswain/index.html"
        - "/about/murphy-tiernan/index.html"
sitemap:
  include_posts:
        - "/index.html"
sitemap:
  change_frequency_name: "change_frequency"
sitemap:
  priority_name: "priority"
collections:
  people:
    title: People
    output: true
    permalink: "/about/:path/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
short_title: MH Resources
description: Consultoria em Saúde Mental
baseurl: /mhresources.tk
permalink: "/:path/"
jekyll-archives:
  enabled: all
  layout: archive
plugins:
- jekyll-seo-tag
- jekyll-menus
- jekyll-feed
- jekyll-archives
